apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: mongodb
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: articles-project

  source:
    repoURL: "https://github.com/jayaprakashbarca/jet-assignment.git"
    targetRevision: main
    path: mongodb

    helm:
      releaseName: mongodb

      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: articles

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5

      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10